### ISSUE TITLE
Fails to remove duplicates / Crashes Sublime

### ISSUE THREAD

**Issue by davidharrison92** [ilyakam/RemoveDuplicateLines#13]
Sublime 3.0 / Build 3170 
MacOS 10.13.4

Using a list of 2200 values (45 distinct values). Can provide the list privately if needed.

**Comment by ilyakam** [comment]
Hi @davidharrison92, this issue should have been fixed in [release 1.2.1](https://github.com/ilyakam/RemoveDuplicateLines/releases/tag/1.2.1) by @Moojuiceman and me. Please try it out first.

If you're still running into this problem, please reopen this issue and attach the file that's causing this bug. You may want to anonymize/obfuscate it because this is a public repository.
